#!/bin/bash

echo start building domainfinder...
go build -o domainfinder
echo start building synonyms...
go build -o ../domainfinder/lib/synonyms
echo start building available...
go build -o ../domainfinder/lib/available
echo start building sprinkle...
go build -o ../domainfinder/lib/sprinkle
echo start building coolify...
go build -o ../domainfinder/lib/coolify
echo start building domainify...
go build -o ../domainfinder/lib/domainify
echo Finished
